apiVersion: v1
kind: Pod
metadata:
  name: posts
spec:
  containers:
    - name: posts
      image: noreengul/posts:0.0.2
      imagePullPolicy: Never
      command: ["sleep"]
      args: ["infinity"]
